title:             Kylie Moden's Blog
email:             kyliemoden@gmail.com
description:       A Blog Theme by Start Bootstrap
author:            Kylie Moden
baseurl:           "/home"
url:               "http://kjm1425.github.io"

# Social Profiles

facebook_username: kyliemoden

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
